### ISSUE TITLE
PLEASE!! DLT645 - 2007 (English Version)

### ISSUE THREAD

**Issue by inventvictor** [MiniLight/electricMeterReader#1]
Hi there, thank you for this repository.

Can you please share the English version of DLT645 - 2007

Thanks in advance

**Comment by AuroraRAS** [comment]
try there:
https://www.slideshare.net/rickyyang3979/dlt645-protocol-english-version

I don't know how to download the doc, but you can view it online.

**Comment by inventvictor** [comment]
Thank you @AuroraRAS 

I have actually seen this but its only 14 pages. The original is about 80 pages that show the parameters like Active Power, Energy, etc.

**Comment by AuroraRAS** [comment]
The usual Chinese standards have a corresponding ISO or ANSI, unfortunately DL/T645-2007 does not have one.

References to IEC1107 and IEC1142 can be found in an earlier version DL/T645-1997. DL/T645-2007 is designed to replace it. These 2 docs may help you.
